# Generated by Django 4.2.18 on 2026-04-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('doctor', 'Doctor'), ('ai_draft', 'AI Draft')], default='doctor', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='encounters.encounter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
