# Generated by Django 4.2.18 on 2026-04-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField()),
                ('triage_level', models.CharField(choices=[('normal', 'Normal'), ('priority', 'Priority'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('queue_status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_progress', 'In Progress'), ('done', 'Done')], default='waiting', max_length=15)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_ticket', to='appointments.appointment')),
            ],
            options={
                'ordering': ['triage_level', 'queue_number'],
            },
        ),
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='mild', max_length=10)),
                ('history_text', models.TextField(blank=True)),
                ('allergies_text', models.TextField(blank=True)),
                ('medications_text', models.TextField(blank=True)),
                ('urgency_inputs', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_form', to='appointments.appointment')),
            ],
        ),
    ]
