# Generated by Django 4.2.18 on 2026-04-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='accepts_new_patients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='ai_feature_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Per-feature AI toggles: {"case_analysis": true, "report_analysis": true, ...}'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Education history — free text or JSON'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='doctors/id_docs/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible on the public doctors page'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='doctors/licenses/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='position',
            field=models.CharField(blank=True, help_text='Title/role inside the clinic', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='services',
            field=models.JSONField(blank=True, default=list, help_text='Services offered — e.g. checkups, surgeries'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_history',
            field=models.JSONField(blank=True, default=list, help_text='List of prior positions'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='{ "mon": ["09:00", "17:00"], ... }'),
        ),
    ]
