# Generated by Django 4.2.18 on 2026-04-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_notes', models.TextField(blank=True)),
                ('assessment_notes', models.TextField(blank=True)),
                ('plan_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encounter', to='appointments.appointment')),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
